# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThreeStageAmplifier.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(738, 410)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("Schematic.png")))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formFrame = QtGui.QFrame(self.frame)
        self.formFrame.setFrameShape(QtGui.QFrame.Box)
        self.formFrame.setFrameShadow(QtGui.QFrame.Sunken)
        self.formFrame.setObjectName(_fromUtf8("formFrame"))
        self.gridLayout = QtGui.QGridLayout(self.formFrame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.RSEdit = QtGui.QLineEdit(self.formFrame)
        self.RSEdit.setObjectName(_fromUtf8("RSEdit"))
        self.gridLayout.addWidget(self.RSEdit, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.formFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.formFrame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.formFrame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.formFrame)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.formFrame)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.Zin1Edit = QtGui.QLineEdit(self.formFrame)
        self.Zin1Edit.setObjectName(_fromUtf8("Zin1Edit"))
        self.gridLayout.addWidget(self.Zin1Edit, 1, 1, 1, 1)
        self.AV1Edit = QtGui.QLineEdit(self.formFrame)
        self.AV1Edit.setObjectName(_fromUtf8("AV1Edit"))
        self.gridLayout.addWidget(self.AV1Edit, 2, 1, 1, 1)
        self.Zo1Edit = QtGui.QLineEdit(self.formFrame)
        self.Zo1Edit.setObjectName(_fromUtf8("Zo1Edit"))
        self.gridLayout.addWidget(self.Zo1Edit, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.formFrame)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.formFrame)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.formFrame)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.formFrame)
        self.formFrame_2 = QtGui.QFrame(self.frame)
        self.formFrame_2.setFrameShape(QtGui.QFrame.Box)
        self.formFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.formFrame_2.setObjectName(_fromUtf8("formFrame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.formFrame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Zin2Edit = QtGui.QLineEdit(self.formFrame_2)
        self.Zin2Edit.setObjectName(_fromUtf8("Zin2Edit"))
        self.gridLayout_2.addWidget(self.Zin2Edit, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.formFrame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.formFrame_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.formFrame_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.formFrame_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.Av2Edit = QtGui.QLineEdit(self.formFrame_2)
        self.Av2Edit.setObjectName(_fromUtf8("Av2Edit"))
        self.gridLayout_2.addWidget(self.Av2Edit, 1, 1, 1, 1)
        self.Zo2Edit = QtGui.QLineEdit(self.formFrame_2)
        self.Zo2Edit.setObjectName(_fromUtf8("Zo2Edit"))
        self.gridLayout_2.addWidget(self.Zo2Edit, 2, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.formFrame_2)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 1, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.formFrame_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 2, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.formFrame_2)
        self.formFrame_3 = QtGui.QFrame(self.frame)
        self.formFrame_3.setFrameShape(QtGui.QFrame.Box)
        self.formFrame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.formFrame_3.setObjectName(_fromUtf8("formFrame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.formFrame_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.formFrame_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.formFrame_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.formFrame_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.Zin3Edit = QtGui.QLineEdit(self.formFrame_3)
        self.Zin3Edit.setObjectName(_fromUtf8("Zin3Edit"))
        self.gridLayout_3.addWidget(self.Zin3Edit, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.formFrame_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 2, 0, 1, 1)
        self.Av3Edit = QtGui.QLineEdit(self.formFrame_3)
        self.Av3Edit.setObjectName(_fromUtf8("Av3Edit"))
        self.gridLayout_3.addWidget(self.Av3Edit, 1, 1, 1, 1)
        self.Zo3Edit = QtGui.QLineEdit(self.formFrame_3)
        self.Zo3Edit.setObjectName(_fromUtf8("Zo3Edit"))
        self.gridLayout_3.addWidget(self.Zo3Edit, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.formFrame_3)
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 1, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.formFrame_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 2, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.formFrame_3)
        self.formFrame_4 = QtGui.QFrame(self.frame)
        self.formFrame_4.setFrameShape(QtGui.QFrame.Box)
        self.formFrame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.formFrame_4.setObjectName(_fromUtf8("formFrame_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.formFrame_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.formFrame_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.formFrame_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 2, 1, 1)
        self.RLEdit = QtGui.QLineEdit(self.formFrame_4)
        self.RLEdit.setObjectName(_fromUtf8("RLEdit"))
        self.gridLayout_4.addWidget(self.RLEdit, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.formFrame_4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 1, 0, 1, 1)
        self.AvOutEdit = QtGui.QLineEdit(self.formFrame_4)
        self.AvOutEdit.setReadOnly(True)
        self.AvOutEdit.setObjectName(_fromUtf8("AvOutEdit"))
        self.gridLayout_4.addWidget(self.AvOutEdit, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.formFrame_4)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.RSEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Zin1Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.AV1Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Zo1Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Zin2Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Av2Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Zo2Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Zin3Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Av3Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.Zo3Edit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QObject.connect(self.RLEdit, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), MainWindow.recalculate)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.RSEdit, self.Zin1Edit)
        MainWindow.setTabOrder(self.Zin1Edit, self.AV1Edit)
        MainWindow.setTabOrder(self.AV1Edit, self.Zo1Edit)
        MainWindow.setTabOrder(self.Zo1Edit, self.Zin2Edit)
        MainWindow.setTabOrder(self.Zin2Edit, self.Av2Edit)
        MainWindow.setTabOrder(self.Av2Edit, self.Zo2Edit)
        MainWindow.setTabOrder(self.Zo2Edit, self.Zin3Edit)
        MainWindow.setTabOrder(self.Zin3Edit, self.Av3Edit)
        MainWindow.setTabOrder(self.Av3Edit, self.Zo3Edit)
        MainWindow.setTabOrder(self.Zo3Edit, self.RLEdit)
        MainWindow.setTabOrder(self.RLEdit, self.AvOutEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Three Stage Amplifier", None))
        self.label.setText(_translate("MainWindow", "Schematic", None))
        self.label_3.setText(_translate("MainWindow", "Rs", None))
        self.label_7.setText(_translate("MainWindow", "k Ohm", None))
        self.label_11.setText(_translate("MainWindow", "Zin1", None))
        self.label_12.setText(_translate("MainWindow", "Av1", None))
        self.label_13.setText(_translate("MainWindow", "Zo1", None))
        self.label_14.setText(_translate("MainWindow", "k Ohm", None))
        self.label_16.setText(_translate("MainWindow", "k Ohm", None))
        self.label_4.setText(_translate("MainWindow", "Zin2", None))
        self.label_8.setText(_translate("MainWindow", "k Ohm", None))
        self.label_17.setText(_translate("MainWindow", "Av2", None))
        self.label_18.setText(_translate("MainWindow", "Zo2", None))
        self.label_22.setText(_translate("MainWindow", "k Ohm", None))
        self.label_5.setText(_translate("MainWindow", "Zin3", None))
        self.label_9.setText(_translate("MainWindow", "k Ohm", None))
        self.label_19.setText(_translate("MainWindow", "Av3", None))
        self.label_20.setText(_translate("MainWindow", "Zo3", None))
        self.label_24.setText(_translate("MainWindow", "k Ohm", None))
        self.label_6.setText(_translate("MainWindow", "RL", None))
        self.label_10.setText(_translate("MainWindow", "k Ohm", None))
        self.label_25.setText(_translate("MainWindow", "Av,out", None))

