# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tank-circuit.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TankCircuit(object):
    def setupUi(self, TankCircuit):
        TankCircuit.setObjectName(_fromUtf8("TankCircuit"))
        TankCircuit.resize(569, 431)
        self.centralwidget = QtGui.QWidget(TankCircuit)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_7 = QtGui.QLabel(self.frame_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_10.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("Schematic.png")))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_10.addWidget(self.label_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8("Equations.png")))
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.frame_7 = QtGui.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_13 = QtGui.QLabel(self.frame_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_17.addWidget(self.label_13)
        self.frame = QtGui.QFrame(self.frame_7)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 7, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 5, 0, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 1, 1)
        self.CtotEdit = QtGui.QLineEdit(self.frame)
        self.CtotEdit.setReadOnly(True)
        self.CtotEdit.setPlaceholderText(_fromUtf8(""))
        self.CtotEdit.setObjectName(_fromUtf8("CtotEdit"))
        self.gridLayout_2.addWidget(self.CtotEdit, 5, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 6, 0, 1, 1)
        self.FminEdit = QtGui.QLineEdit(self.frame)
        self.FminEdit.setEnabled(True)
        self.FminEdit.setReadOnly(True)
        self.FminEdit.setObjectName(_fromUtf8("FminEdit"))
        self.gridLayout_2.addWidget(self.FminEdit, 6, 1, 1, 1)
        self.FmaxEdit = QtGui.QLineEdit(self.frame)
        self.FmaxEdit.setEnabled(True)
        self.FmaxEdit.setReadOnly(True)
        self.FmaxEdit.setObjectName(_fromUtf8("FmaxEdit"))
        self.gridLayout_2.addWidget(self.FmaxEdit, 7, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.frame)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 7, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 3, 0, 1, 1)
        self.CbsetEdit = QtGui.QLineEdit(self.frame)
        self.CbsetEdit.setPlaceholderText(_fromUtf8(""))
        self.CbsetEdit.setObjectName(_fromUtf8("CbsetEdit"))
        self.gridLayout_2.addWidget(self.CbsetEdit, 3, 1, 1, 1)
        self.CvarminEdit = QtGui.QLineEdit(self.frame)
        self.CvarminEdit.setPlaceholderText(_fromUtf8(""))
        self.CvarminEdit.setObjectName(_fromUtf8("CvarminEdit"))
        self.gridLayout_2.addWidget(self.CvarminEdit, 0, 1, 1, 1)
        self.CspreadEdit = QtGui.QLineEdit(self.frame)
        self.CspreadEdit.setPlaceholderText(_fromUtf8(""))
        self.CspreadEdit.setObjectName(_fromUtf8("CspreadEdit"))
        self.gridLayout_2.addWidget(self.CspreadEdit, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 2, 0, 1, 1)
        self.LEdit = QtGui.QLineEdit(self.frame)
        self.LEdit.setPlaceholderText(_fromUtf8(""))
        self.LEdit.setObjectName(_fromUtf8("LEdit"))
        self.gridLayout_2.addWidget(self.LEdit, 4, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 6, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 5, 2, 1, 1)
        self.CvarmaxEdit = QtGui.QLineEdit(self.frame)
        self.CvarmaxEdit.setPlaceholderText(_fromUtf8(""))
        self.CvarmaxEdit.setObjectName(_fromUtf8("CvarmaxEdit"))
        self.gridLayout_2.addWidget(self.CvarmaxEdit, 1, 1, 1, 1)
        self.verticalLayout_17.addWidget(self.frame)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        self.verticalLayout_14.addWidget(self.frame_7)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addWidget(self.frame_6)
        self.gridLayout.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        TankCircuit.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(TankCircuit)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TankCircuit.setStatusBar(self.statusbar)

        self.retranslateUi(TankCircuit)
        QtCore.QObject.connect(self.CvarminEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), TankCircuit.recalculate)
        QtCore.QObject.connect(self.LEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), TankCircuit.recalculate)
        QtCore.QObject.connect(self.CbsetEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), TankCircuit.recalculate)
        QtCore.QObject.connect(self.CtotEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), TankCircuit.recalculate)
        QtCore.QObject.connect(self.CspreadEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), TankCircuit.recalculate)
        QtCore.QObject.connect(self.CvarmaxEdit, QtCore.SIGNAL(_fromUtf8("editingFinished()")), TankCircuit.recalculate)
        QtCore.QMetaObject.connectSlotsByName(TankCircuit)
        TankCircuit.setTabOrder(self.CvarminEdit, self.CvarmaxEdit)
        TankCircuit.setTabOrder(self.CvarmaxEdit, self.CspreadEdit)
        TankCircuit.setTabOrder(self.CspreadEdit, self.CbsetEdit)
        TankCircuit.setTabOrder(self.CbsetEdit, self.LEdit)
        TankCircuit.setTabOrder(self.LEdit, self.CtotEdit)
        TankCircuit.setTabOrder(self.CtotEdit, self.FminEdit)
        TankCircuit.setTabOrder(self.FminEdit, self.FmaxEdit)

    def retranslateUi(self, TankCircuit):
        TankCircuit.setWindowTitle(_translate("TankCircuit", "Tank Circuit", None))
        self.label_7.setText(_translate("TankCircuit", "Schematic", None))
        self.label_11.setText(_translate("TankCircuit", "Equations", None))
        self.label_13.setText(_translate("TankCircuit", "Calculate", None))
        self.label_3.setText(_translate("TankCircuit", "pF", None))
        self.label_4.setText(_translate("TankCircuit", "pF", None))
        self.label_5.setText(_translate("TankCircuit", "nH", None))
        self.label_6.setText(_translate("TankCircuit", "MHz", None))
        self.label_18.setText(_translate("TankCircuit", "L", None))
        self.label_19.setText(_translate("TankCircuit", "Ctot", None))
        self.label.setText(_translate("TankCircuit", "pF", None))
        self.label_2.setText(_translate("TankCircuit", "pF", None))
        self.label_14.setText(_translate("TankCircuit", "Cvarmax", None))
        self.label_20.setText(_translate("TankCircuit", "Fmin", None))
        self.label_21.setText(_translate("TankCircuit", "Fmax", None))
        self.label_17.setText(_translate("TankCircuit", "Cbset", None))
        self.label_16.setText(_translate("TankCircuit", "Cspread", None))
        self.label_15.setText(_translate("TankCircuit", "Cvarmin", None))
        self.label_9.setText(_translate("TankCircuit", "MHz", None))
        self.label_10.setText(_translate("TankCircuit", "pF", None))

