# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'common-emitter.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CommonEmitter(object):
    def setupUi(self, CommonEmitter):
        CommonEmitter.setObjectName(_fromUtf8("CommonEmitter"))
        CommonEmitter.resize(775, 637)
        self.centralwidget = QtGui.QWidget(CommonEmitter)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_7 = QtGui.QLabel(self.frame_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_10.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("schematic.png")))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_10.addWidget(self.label_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_12.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.frame_5)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8("r-pi-beta-equivalent.png")))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_12.addWidget(self.label_10)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.frame_7 = QtGui.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_13 = QtGui.QLabel(self.frame_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_17.addWidget(self.label_13)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_15 = QtGui.QLabel(self.frame_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.lineEdit = QtGui.QLineEdit(self.frame_7)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_14 = QtGui.QLabel(self.frame_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_16 = QtGui.QLabel(self.frame_7)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtGui.QLabel(self.frame_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_3 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_7.setEnabled(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.label_18 = QtGui.QLabel(self.frame_7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.frame_7)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtGui.QLabel(self.frame_7)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(self.frame_7)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtGui.QLabel(self.frame_7)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_22)
        self.verticalLayout_17.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        self.verticalLayout_14.addWidget(self.frame_7)
        self.label_11 = QtGui.QLabel(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_14.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.frame_6)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8("equations.png")))
        self.label_12.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_14.addWidget(self.label_12)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addWidget(self.frame_6)
        self.gridLayout.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        CommonEmitter.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(CommonEmitter)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CommonEmitter.setStatusBar(self.statusbar)

        self.retranslateUi(CommonEmitter)
        QtCore.QObject.connect(self.lineEdit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), CommonEmitter.recalculate)
        QtCore.QObject.connect(self.lineEdit_2, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), CommonEmitter.recalculate)
        QtCore.QObject.connect(self.lineEdit_3, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), CommonEmitter.recalculate)
        QtCore.QObject.connect(self.lineEdit_4, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), CommonEmitter.recalculate)
        QtCore.QObject.connect(self.lineEdit_5, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), CommonEmitter.recalculate)
        QtCore.QObject.connect(self.lineEdit_6, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), CommonEmitter.recalculate)
        QtCore.QMetaObject.connectSlotsByName(CommonEmitter)

    def retranslateUi(self, CommonEmitter):
        CommonEmitter.setWindowTitle(_translate("CommonEmitter", "Common Emitter Feedback Amplifier", None))
        self.label_7.setText(_translate("CommonEmitter", "Schematic", None))
        self.label_9.setText(_translate("CommonEmitter", "Small Signal Equivalent Circuit", None))
        self.label_13.setText(_translate("CommonEmitter", "Calculate", None))
        self.label_15.setText(_translate("CommonEmitter", "ICQ", None))
        self.lineEdit.setPlaceholderText(_translate("CommonEmitter", "1 mA", None))
        self.lineEdit_2.setPlaceholderText(_translate("CommonEmitter", "10k Ohm", None))
        self.label_14.setText(_translate("CommonEmitter", "RS", None))
        self.label_16.setText(_translate("CommonEmitter", "RB", None))
        self.label_17.setText(_translate("CommonEmitter", "RC", None))
        self.lineEdit_3.setPlaceholderText(_translate("CommonEmitter", "470k Ohm", None))
        self.lineEdit_4.setPlaceholderText(_translate("CommonEmitter", "4.7k Ohm", None))
        self.lineEdit_5.setPlaceholderText(_translate("CommonEmitter", "4.7k Ohm", None))
        self.lineEdit_6.setPlaceholderText(_translate("CommonEmitter", "100", None))
        self.label_18.setText(_translate("CommonEmitter", "RL", None))
        self.label_19.setText(_translate("CommonEmitter", "Beta", None))
        self.label_20.setText(_translate("CommonEmitter", "Av", None))
        self.label_21.setText(_translate("CommonEmitter", "Zo", None))
        self.label_22.setText(_translate("CommonEmitter", "Zin", None))
        self.label_11.setText(_translate("CommonEmitter", "Equations", None))

